services:
  - type: web
    name: travel-health-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: WS_MAX_CONNECTIONS_PER_CLIENT
        value: 10
      - key: WS_RATE_LIMIT_WINDOW_MS
        value: 60000
      - key: WS_MAX_REQUESTS_PER_WINDOW
        value: 1000
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: travel-health-data
      mountPath: /data
      sizeGB: 1
